chore: add gradle clean task
aws-amplify/amplify-android pull request #1134
Opened 2021-01-26 22:15 UTC by raphkim

*Issue #, if available:*

*Description of changes:*
Add `clean` task as a pre-requisite for `build`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-26 22:43 UTC, richardmcclellan commented
The commit to add `clean` looks good, but looks like you need to rebase with `main`.

2021-01-27 04:50 UTC, jamesonwilliams requested changes
Looks like some unrelated changes snuck in here?

2021-01-27 04:50 UTC, jamesonwilliams commented on core/src/main/java/com/amplifyframework/core/model/query/QuerySortBy.java
> +                "model=" + (modelName == null ? null : Wrap.inSingleQuotes(modelName)) +
```suggestion
                "modelName=" + (modelName == null ? null : Wrap.inSingleQuotes(modelName)) +
```

2021-02-15 17:12 UTC, richardmcclellan commented
Closing, since `clean` was added in: https://github.com/aws-amplify/amplify-android/pull/1166

2021-02-15 17:12 UTC, closed without merging