feat: Add support for custom prefix resolver
aws-amplify/amplify-android pull request #1659
Opened 2022-02-12 01:03 UTC by sdhuka

*Issue #, if available:*
#910 
*Description of changes:*
- Add support for custom prefix resolver for storage category.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-15 14:41 UTC, lawmicha commented on aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadInputStreamOperation.java
> +                                    inputStream,
nit: bring `serviceKey` down a line to `inputStream` and `objectMetadata`

2022-02-15 14:44 UTC, lawmicha commented on aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageListOperation.java
> +                        onSuccess.accept(StorageListResult.fromItems(listedItems));
lines 85-87 duplicate with 95-97

2022-02-15 14:47 UTC, lawmicha commented on aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperationTest.kt
> +        Mockito.verify(storageService).downloadToFile(expectedKey, tempFile)
verifying `""` is good, can we add another test to verify expectedKey == "customPublic/123.png" when the custom prefix resolver returns "customPublic/" for the public access level? Then do we also need to these 3 tests for other operations?

2022-02-15 22:26 UTC, lawmicha approved these changes
LGTM

2022-02-16 17:53 UTC, div5yesh commented on aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/configuration/AWSS3StoragePluginConfiguration.kt
> +    class Builder {
Builder does not have `build` method.

2022-02-16 21:19 UTC, div5yesh commented on aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/configuration/AWSS3PluginPrefixResolver.kt
> +            cognitoAuthProvider.identityId
This is just an assignment, which will be always successful even if identityId is null. `else` is not reachable.

2022-02-16 21:19 UTC, div5yesh approved these changes

2022-02-16 21:20 UTC, div5yesh requested changes
Left few comments.

2022-02-16 21:25 UTC, div5yesh approved these changes
LGTM

2022-02-17 14:45 UTC, merged

2022-06-15 12:15 UTC, bilal-aslam96 commented
Thank you this solution works.