Dev preview merge
aws-amplify/amplify-android pull request #1752
Opened 2022-05-24 23:17 UTC by tjleing

Correctly merge main commits into dev-preview branch before release

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-25 15:59 UTC, sktimalsina requested changes

2022-05-25 17:48 UTC, tjleing commented on CHANGELOG.md
> +[See all changes between 1.35.0 and 1.36.0-dev-preview.0](https://github.com/aws-amplify/amplify-android/compare/release_v1.35.5...release_v1.36.0-dev-preview.0)
Good catch, thank you!  I had wondered why changes from 1.35.1 weren't in the merge...

2022-05-26 00:30 UTC, div5yesh approved these changes

2022-05-26 07:29 UTC, sktimalsina commented on CHANGELOG.md
> +[See all changes between 1.35.0 and 1.36.0-dev-preview.0](https://github.com/aws-amplify/amplify-android/compare/release_v1.35.5...release_v1.36.0-dev-preview.0)
This particular log still does not seem to be in right position. `1.36.0-dev-preview` should sit between `1.35.2` and `1.35.3` and `1.36.5-dev-preview ` above `1.35.5`.

2022-05-26 22:23 UTC, sktimalsina submitted a review, later dismissed

2022-05-26 22:41 UTC, sktimalsina approved these changes

2022-05-27 17:13 UTC, div5yesh approved these changes

2022-05-31 17:04 UTC, merged