added implementation for updatepassword
aws-amplify/amplify-android pull request #1788
Opened 2022-06-20 16:39 UTC by banji180

*[Issue #, if available:](https://app.asana.com/0/0/1202262968555214/f)*

*Description of changes: Added implementation for update*

*How did you test these changes?*
This is preliminary file. Test will be added later

*Documentation update required?*
No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-21 00:31 UTC, div5yesh requested changes

2022-06-21 00:31 UTC, div5yesh commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
> +            GlobalScope.launch {
Check if user is signed in by checking the current state of AuthStateMachine using `getCurrentState`.

2022-06-21 00:31 UTC, div5yesh commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
> +                onSuccess.call()
Please add unit tests.

2022-06-21 14:37 UTC, gpanshu commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
> +        {
Formatting is off, please run `./gradlew ktlintFormat`

2022-06-21 14:39 UTC, gpanshu commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
> +    private fun _updatePassword(token: String,
Call this val accessToken too

2022-06-21 14:40 UTC, gpanshu commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
> +                val cognitoClient = configureCognitoClients().cognitoIdentityProviderClient?.changePassword(changePasswordRequest)
cognitoClient is not used anymore and potentially can be deleted?

2022-07-14 17:40 UTC, gpanshu commented
Can you update the name to conform to the PR title guideline

2022-07-26 19:31 UTC, div5yesh approved these changes

2022-07-27 13:19 UTC, gpanshu approved these changes

2022-07-27 16:57 UTC, merged