Sdhuka/pinpoint hubevents
aws-amplify/amplify-android pull request #1792
Opened 2022-06-22 14:02 UTC by sdhuka

*Issue #, if available:*

*Description of changes:*
- Send hub events with all the successfully submitted events on flushEvents.
- [PR]() with AWS SDK Changes

*How did you test these changes?*
- Added instrumentation test to assert hub event is send after calling flush events.
- Testing using sample app.

*Documentation update required?*
- [ ] Yes (tbd)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-22 18:16 UTC, gpanshu submitted a review, later dismissed

2022-06-22 19:29 UTC, div5yesh requested changes

2022-06-22 19:29 UTC, div5yesh commented on aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.java
> +                    .create(AnalyticsHubEventNames.FLUSH_EVENTS, analyticsEvents)),
Hub event class name should be `AnalyticsChannelEventName` for consistency with other hub event classes.

2022-06-22 19:29 UTC, div5yesh commented on aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AutoEventSubmitter.java
>          this.handler = new Handler(handlerThread.getLooper());
Should we remove `analyticsClient` from the constructor since APIs are directly accessed using plugin now?

2022-06-23 05:17 UTC, div5yesh approved these changes

2022-06-23 16:31 UTC, tjleing approved these changes
LGTM!

2022-06-23 17:58 UTC, merged