Fix for flutter backtick
aws-amplify/amplify-android pull request #1866
Opened 2022-07-30 22:54 UTC by poojamat

- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
Flutter fix for back ticks
*Issue #, if available:*

*Description of changes:*

*How did you test these changes?*
(Please add a line here how the changes were tested)

- [ ] Added Unit Tests
- [ ] Tested on frontend (Add Screenshots)
- [ ] Successful logs (Attach them to the PR)

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-01 17:49 UTC, HuiSF commented on aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
> +                && predicateOperationField.startsWith("@@") && predicateOperation.modelName() != null) {
```suggestion
                && predicateOperationField.startsWith("@@") && predicateOperation.modelName() == null) {
```

2022-08-01 19:12 UTC, HuiSF approved these changes

2022-08-01 20:04 UTC, HuiSF submitted a review, later dismissed

2022-08-11 19:24 UTC, HuiSF approved these changes

2022-08-11 19:27 UTC, sktimalsina requested changes
Please change the title of PR as recommended so that it shows up correctly in changelist as mentioned in the checklist in PR template:
https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines
fix(api): <rest of the title>

2022-08-11 20:05 UTC, eeatonaws reviewed
Are there any tests we can add for this fix?

2022-08-11 23:07 UTC, sktimalsina approved these changes

2022-08-11 23:46 UTC, merged