Adding retry ability to mutation processor
aws-amplify/amplify-android pull request #1906
Opened 2022-08-24 05:16 UTC by poojamat

- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*
#1794 
*Description of changes:*
Adding retry functionality to mutation processor.
*How did you test these changes?*
(Please add a line here how the changes were tested)

- [ ] Added Unit Tests
- [ ] Added Integration Tests

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-24 17:10 UTC, sktimalsina requested changes
Please update the PR title and check the box in PR message.

2022-09-06 18:12 UTC, lawmicha approved these changes

2022-09-07 23:33 UTC, drochetti approved these changes

2022-09-08 21:01 UTC, lawmicha approved these changes

2022-09-08 21:01 UTC, drochetti approved these changes

2022-09-08 21:03 UTC, sktimalsina approved these changes

2022-09-08 21:03 UTC, merged