Update SignOut Flow
aws-amplify/amplify-android pull request #1915
Opened 2022-08-26 14:29 UTC by tylerjroach

- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*

*Description of changes:*
* Remove option to sign out locally without calling revoke token (matches iOS and state machine)
* Nullability improvements so that SignedInData is never null
* Remove SignOut while already SignedOut flow

*How did you test these changes?*
(Please add a line here how the changes were tested)

- [ ] Added Unit Tests
- [ ] Added Integration Tests

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-26 16:21 UTC, gpanshu submitted a review, later dismissed

2022-08-26 18:57 UTC, div5yesh requested changes
Please also consider guest access (UnAuth case).

2022-08-26 18:57 UTC, div5yesh commented on aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/AuthenticationState.kt
> -                    authenticationEvent is AuthenticationEvent.EventType.SignOutRequested -> {
This is required to clear UnAuth session.

2022-08-26 18:57 UTC, div5yesh commented on aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/AuthenticationState.kt
> +                builder.updateSignInState(it.newState)
🚀

2022-08-26 18:57 UTC, div5yesh commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/AuthenticationCognitoActions.kt
> +        signedInData: SignedInData
In case when it is guest session, `signedInData` will be null.

2022-08-26 18:57 UTC, div5yesh commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/AuthenticationCognitoActions.kt
> +        signedInData: SignedInData
For guest session, we will only be doing local sign out.

2022-09-08 19:31 UTC, gpanshu submitted a review, later dismissed

2022-09-09 16:10 UTC, gpanshu approved these changes

2022-09-09 18:36 UTC, sktimalsina approved these changes

2022-09-09 18:57 UTC, merged