chore(auth): code cleanup and PR feedback follow up
aws-amplify/amplify-android pull request #1942
Opened 2022-09-08 04:48 UTC by div5yesh

- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*

*Description of changes:*

*How did you test these changes?*
(Please add a line here how the changes were tested)

- [ ] Added Unit Tests
- [ ] Added Integration Tests

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-20 16:13 UTC, gpanshu commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
> +                        _deleteUser(accessToken!!, onSuccess, onError)
Can we avoid using `!!` ?

2022-09-20 16:14 UTC, gpanshu requested changes
Remove !!

2022-09-23 13:36 UTC, gpanshu approved these changes

2022-10-04 16:13 UTC, tylerjroach approved these changes

2022-10-05 00:27 UTC, merged