feat(Auth): Dev preview devicesrp
aws-amplify/amplify-android pull request #1946
Opened 2022-09-09 19:24 UTC by gpanshu

- [ x] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*

*Description of changes:*
Device SRP is triggered when a user srp operation is performed and all MFA challenges are answered. At that time if the server responds with device metadata we do a confirm device operation and store the device credentials.
Once the user logs out and logs back in we receive a device SRP challenge which is when we conduct a device srp respondToAuth and then a respondtoAuth again for DevicePasswordVerifier (This is present in the DeviceSRPSignInStateMachine and its actions and events respectively.)

*How did you test these changes?*
(Please add a line here how the changes were tested)

Tests are coming in Soon

- [x ] Added Unit Tests
- [ ] Added Integration Tests

*Documentation update required?*
- [x ] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-13 23:01 UTC, tylerjroach commented on aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCognitoActions.kt
> +            val _idToken = event.confirmDeviceParams[KEY_ID_TOKEN]
nit: why the underscores? This isn't part of Kotlin/Android codestyle

2022-09-14 23:06 UTC, tylerjroach approved these changes

2022-09-15 19:34 UTC, div5yesh requested changes
Needs manual testing.

2022-09-20 01:01 UTC, div5yesh approved these changes

2022-09-20 16:02 UTC, merged