Dengdan stress test
aws-amplify/amplify-android pull request #2146
Opened 2022-11-30 15:51 UTC by dengdan154

- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*

*Description of changes:*

*How did you test these changes?*
(Please add a line here how the changes were tested)

- [ ] Added Unit Tests
- [ ] Added Integration Tests

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-30 18:43 UTC, gpanshu commented on aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/StorageStressTest.kt
> +//            // Upload 25 small test files
Nit: double commented out. Remove one `||`

2022-11-30 18:45 UTC, gpanshu commented on configuration/publishing.gradle
> + * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
If you are changing the copywright shouldnt it be to 2022?

2022-11-30 18:47 UTC, gpanshu requested changes
Update copyright info on all changed files to 2022 and add copyright headers wherever missing.

2022-11-30 18:47 UTC, gpanshu commented on maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/MapViewStressTest.kt
> +package com.amplifyframework.geo.maplibre
copyright header missing

2022-11-30 18:47 UTC, gpanshu commented on scripts/temp.sh
> +./gradlew :aws-analytics-pinpoint:connectedAndroidTest
Whats the purpose of this script, can you add some comments in here to justify adding something to scripts folder?

2022-11-30 18:47 UTC, gpanshu commented on aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelWithMetadataAdapter.java
> -        ModelMetadata modelMetadata = src.getSyncMetadata();
update copyright to 2022

2022-11-30 23:08 UTC, tjleing commented on aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/PinpointAnalyticsStressTest.kt
> +                .addProperty("AnalyticsStringProperty1", "Pancakes")
```kotlin
val event = <>
for (i in 0..50) {
   event.addProperty("AnalyticsStringProperty${i}", "Pancakes");
}
```

2022-11-30 23:08 UTC, tjleing commented on aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/PinpointAnalyticsStressTest.kt
> +            .add("SomeUserAttribute1", "User attribute value")
see above 😄

2022-11-30 23:08 UTC, tjleing commented on scripts/aws-datastore/src/androidTest/res/raw/amplifyconfigurationupdated.json
> +/Users/dengdan/.aws-amplify/amplify-android/aws-datastore/src/androidTest/res/raw/amplifyconfigurationupdated.json
please delete -- we might want to remove this file (symlink?) from the cloud so that this doesn't accidentally get committed in the future

2022-11-30 23:10 UTC, tjleing commented on scripts/aws-datastore/src/androidTest/res/raw/amplifyconfigurationupdated.json
> +/Users/dengdan/.aws-amplify/amplify-android/aws-datastore/src/androidTest/res/raw/amplifyconfigurationupdated.json
and/or adding to .gitignore

2022-12-01 16:19 UTC, dengdan154 commented on aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/PinpointAnalyticsStressTest.kt
> +                .addProperty("AnalyticsStringProperty1", "Pancakes")
THIS is very helpful thanks :)

2022-12-01 19:08 UTC, div5yesh approved these changes
LGTM

2022-12-02 17:56 UTC, closed without merging