analytics test fail fix
aws-amplify/amplify-android pull request #2162
Opened 2022-12-06 22:52 UTC by dengdan154

- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*

*Description of changes:*

*How did you test these changes?*
(Please add a line here how the changes were tested)

- [ ] Added Unit Tests
- [ ] Added Integration Tests

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-07 20:43 UTC, gpanshu submitted a review, later dismissed

2022-12-09 21:24 UTC, sdhuka requested changes

2022-12-09 21:24 UTC, sdhuka commented on aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/targeting/TargetingClient.kt
> +        Log.i("REQUEST!", updateEndpointRequest.toString())
revert this logging added for debugging.

2022-12-12 16:23 UTC, tjleing approved these changes
15 commits 😅

2022-12-20 14:41 UTC, closed without merging