[DO NOT MERGE] [WIP] Draft PR for recoverability improvements
aws-amplify/amplify-android pull request #2201
Opened 2022-12-23 23:51 UTC by manueliglesias

- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*

*Description of changes:*

*How did you test these changes?*
(Please add a line here how the changes were tested)

- [ ] Added Unit Tests
- [ ] Added Integration Tests

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-29 23:34 UTC, mikepschneider requested changes

2022-12-30 19:38 UTC, manueliglesias commented on aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
> +                    // TODO: Check if there is applicable data, if so, emit it but also log the errors.
As discussed offline, this `TODO` will be removed since it is already been tracked internally.

2022-12-30 19:40 UTC, manueliglesias commented on aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
> +                    emitter.onError(new DataStoreException.IrRecoverableException(
As discussed offline, this is not a new class introduced by this PR and it's been used elsewhere. Renaming it now is out of scope of this PR.

2022-12-30 19:40 UTC, manueliglesias commented on aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/RetryHandler.java
> +     * Method returns jittered delay time in milliseconds.
Sounds good

2022-12-30 19:54 UTC, manueliglesias commented on aws-api/src/main/java/com/amplifyframework/api/aws/auth/ApiKeyRequestDecorator.java
> +                      .addHeader(X_API_KEY, apiKey)
This was added as it was useful when debugging interactively (stepping statement-by-statement), as discussed offline, it will be removed.

2023-01-01 22:51 UTC, manueliglesias commented on aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLOperation.java
> +                    LOG.debug(String.format("Response: %s", jsonResponse));
This was discussed internally and the issue of network traffic logging will be addressed separately.

2023-01-03 19:16 UTC, mikepschneider submitted a review, later dismissed

2023-01-03 20:48 UTC, div5yesh submitted a review, later dismissed

2023-01-10 23:55 UTC, div5yesh approved these changes

2023-02-01 16:23 UTC, sdhuka approved these changes

2023-02-01 16:23 UTC, gpanshu approved these changes

2023-02-01 16:41 UTC, merged