chore: Add restrict to annotation
aws-amplify/amplify-android pull request #2349
Opened 2023-03-20 21:18 UTC by eeatonaws

- [x] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:* N/A

*Description of changes:* Add an annotation similar to Android's RestrictTo since RestrictTo does not work for Kotlin classes and APIs.

*How did you test these changes?*
Tested the annotation in a sample app.

*Documentation update required?*
- [x] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] Added Unit Tests
- [ ] Added Integration Tests
- [x] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-20 22:00 UTC, div5yesh submitted a review, later dismissed

2023-03-21 12:03 UTC, mattcreaser requested changes

2023-03-21 12:03 UTC, mattcreaser commented on annotations/src/main/java/com/amplifyframework/annotations/RestrictToAmplify.kt
> +public annotation class RestrictToAmplify
Can we go with `InternalAmplifyApi` - that would be more consistent with other libraries.

Examples:
[InternalCoroutinesApi](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-internal-coroutines-api/)
[InternalComposeApi](https://developer.android.com/reference/kotlin/androidx/compose/runtime/InternalComposeApi)
[InternalSdkApi](https://github.com/awslabs/aws-sdk-kotlin/blob/177b444b561fa99a6eda0b641307e462cb192cb8/aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/Annotations.kt) - aws kotlin sdk

2023-03-21 12:08 UTC, mattcreaser commented
Can we also change existing instances of RestrictTo in this PR?

2023-03-21 13:46 UTC, tylerjroach commented
> Can we also change existing instances of RestrictTo in this PR?

@mattcreaser I had suggested leaving RestrictTo in for for Java. Thoughts?

2023-03-21 14:30 UTC, eeatonaws commented
> > Can we also change existing instances of RestrictTo in this PR?
> 
> @mattcreaser I had suggested leaving RestrictTo in for for Java. Thoughts?

Instances of RestrictTo have been replaced with InternalAmplifyApi.

2023-03-21 14:36 UTC, tylerjroach approved these changes

2023-03-21 14:42 UTC, mattcreaser approved these changes

2023-03-21 14:43 UTC, sdhuka approved these changes

2023-03-21 15:13 UTC, merged