chore: Add canary tests
aws-amplify/amplify-android pull request #2454
Opened 2023-05-15 21:15 UTC by eeatonaws

- [x] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:* N/A

*Description of changes:* Add canary tests.

*How did you test these changes?*
(Please add a line here how the changes were tested)

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] Added Unit Tests
- [ ] Added Integration Tests
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-17 21:22 UTC, div5yesh commented on aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AuthCanaryTest.kt
> +    fun deleteUser() {
Can we use admin API to delete the user?

We are signing up new users before a lot of tests. We should be deleting them after the test is complete.

2023-05-17 21:22 UTC, div5yesh requested changes
Need to fix user deletion.

2023-05-24 22:16 UTC, eeatonaws commented
> Need to fix user deletion.

Temporary users signed up during the test are now deleted after the test finishes.

2023-05-25 19:43 UTC, div5yesh approved these changes

2023-06-12 15:37 UTC, sdhuka approved these changes

2023-06-12 16:06 UTC, merged